export function LogoIcon() {
  return (
    <svg
      className="text"
      width="340"
      height="340"
      viewBox="0 0 340 340"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g id="clock" transform="translate(170, 170)">
        <circle
          cx="0"
          cy="0"
          r="150"
          fill="none"
          stroke="black"
          stroke-width="40"
        />
        <line
          x1="0"
          y1="0"
          x2="0"
          y2="-100"
          className="text"
          stroke-width="40"
          stroke-linecap="round"
        />
        <line
          x1="0"
          y1="0"
          x2="80"
          y2="0"
          stroke="black"
          stroke-width="20"
          stroke-linecap="round"
        />
        <line
          x1="0"
          y1="-165"
          x2="0"
          y2="-135"
          stroke="black"
          stroke-width="10"
          stroke-linecap="round"
        />
        <line
          x1="165"
          y1="0"
          x2="135"
          y2="0"
          stroke="black"
          stroke-width="10"
          stroke-linecap="round"
        />
        <line
          x1="0"
          y1="165"
          x2="0"
          y2="135"
          stroke="black"
          stroke-width="10"
          stroke-linecap="round"
        />
        <line
          x1="-165"
          y1="0"
          x2="-135"
          y2="0"
          stroke="black"
          stroke-width="10"
          stroke-linecap="round"
        />
      </g>
    </svg>
  );
}
