package api

import "net/http"

func registerRoutes(r *router, api *API) {
	r.Get("/health", api.HealthCheck)

	r.Route("/api/v1", func(r *router) {
		r.Get("/health", api.HealthCheck)
	})
}

type HealthCheckResponse struct {
	Version        string `json:"version"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	DatabaseStatus int    `json:"database_status"`
}

// HealthCheck endpoint indicates if the gotrue api service is available
func (a *API) HealthCheck(w http.ResponseWriter, r *http.Request) error {
	var dbStatus int
	if sqlDb, err := a.db.DB(); err == nil {
		if err := sqlDb.Ping(); err == nil {
			dbStatus = 1
		}
	}
	return sendJSON(w, http.StatusOK, HealthCheckResponse{
		Version:        "0.0.1",
		Name:           "Wakana",
		Description:    "Wakana is an api for developer activity logs generated by IDE plugins",
		DatabaseStatus: dbStatus,
	}, "", "")
}
