env: production

server:
  listen_ipv4: 127.0.0.1
  listen_ipv6:
  tls_cert_path:
  tls_key_path:
  port: 3000
  base_path: /
  public_url: http://localhost:3000

app:
  aggregation_time: "02:15"
  report_time_weekly: "fri,18:00"
  heartbeat_max_age: 87600h # 10 years
  inactive_days: 7
  custom_languages:
    vue: Vue
    jsx: JSX
    svelte: Svelte

db:
  host: 127.0.0.1
  port: 56257
  user: root
  password:
  name: defaultdb
  dialect: cockroach
  charset:
  max_conn: 2
  ssl: false
  automgirate_fail_silently: false

security:
  password_salt:
  insecure_cookies: true
  cookie_max_age: 172800
  allow_signup: true
  expose_metrics: true
  signup_max_rate: 999/1s
  login_max_rate: 999/1s
  password_reset_max_rate: 999/1s
